src/SidDmb/SidDmb.Web/Controllers/AtraksiController.cs
using Microsoft.AspNetCore.Mvc;
using SidDmb.Domain.Abstracts;
using SidDmb.Domain.CollaborationFunction.ModulManajemenEvent.PengelolaanEvent;
using SidDmb.Domain.MasterDataFunction.ModulBudaya;
using SidDmb.Domain.MasterDataFunction.ModulBudaya.ArtefakBudayas;
using SidDmb.Domain.MasterDataFunction.ModulBudaya.SeniBudayas;
using SidDmb.Domain.MasterDataFunction.ModulBudaya.SitusBudayas;
using SidDmb.Domain.MasterDataFunction.ModulBudaya.UpacaraBudayas;
using SidDmb.Domain.MasterDataFunction.ModulPreneur.ProdukLokals;
using SidDmb.Domain.MasterDataFunction.ModulWisata.DestinasiWisatas;

namespace SidDmb.Web.Controllers;

public class AtraksiController : Controller
{
    private readonly IRepositoriDestinasiWisata _repositoriDestinasiWisata;
    private readonly IRepositoriProdukLokal _repositoriProdukLokal;
    private readonly IRepositoriArtefakBudaya _repositoriArtefakBudaya;
    private readonly IRepositoriSitusBudaya _repositoriSitusBudaya;
    private readonly IRepositoriSeniBudaya _repositoriSeniBudaya;
    private readonly IRepositoriUpacaraBudaya _repositoriUpacaraBudaya;
    private readonly IRepositoriEvent _repositoriEvent;
    private readonly IRepositoriKomentar _repositoriKomentar;
    private readonly IUnitOfWork _unitOfWork;

    public AtraksiController(
        IRepositoriDestinasiWisata repositoriDestinasiWisata,
        IRepositoriProdukLokal repositoriProdukLokal,
        IRepositoriArtefakBudaya repositoriArtefakBudaya,
        IRepositoriSitusBudaya repositoriSitusBudaya,
        IRepositoriSeniBudaya repositoriSeniBudaya,
        IRepositoriUpacaraBudaya repositoriUpacaraBudaya,
        IRepositoriEvent repositoriEvent,
        IRepositoriKomentar repositoriKomentar,
        IUnitOfWork unitOfWork)
    {
        _repositoriDestinasiWisata = repositoriDestinasiWisata;
        _repositoriProdukLokal = repositoriProdukLokal;
        _repositoriArtefakBudaya = repositoriArtefakBudaya;
        _repositoriSitusBudaya = repositoriSitusBudaya;
        _repositoriSeniBudaya = repositoriSeniBudaya;
        _repositoriUpacaraBudaya = repositoriUpacaraBudaya;
        _repositoriEvent = repositoriEvent;
        _repositoriKomentar = repositoriKomentar;
        _unitOfWork = unitOfWork;
    }

    public IActionResult Index() => View();

    public async Task<IActionResult> Destinasi() => View(await _repositoriDestinasiWisata.GetAll());

    public async Task<IActionResult> Artefak() => View(await _repositoriArtefakBudaya.GetAll());

    public async Task<IActionResult> Seni() => View(await _repositoriSeniBudaya.GetAll());

    public async Task<IActionResult> Situs() => View(await _repositoriSitusBudaya.GetAll());

    public async Task<IActionResult> Upacara() => View(await _repositoriUpacaraBudaya.GetAll());

    public async Task<IActionResult> ProdukLokal() => View(await _repositoriProdukLokal.GetAll());

    public async Task<IActionResult> DetailDestinasi(string id)
    {
        var resultId = IdDestinasi.Create(id);
        if (resultId.IsFailure) return BadRequest();

        var destinasi = await _repositoriDestinasiWisata.Get(resultId.Value);
        if (destinasi is null) return NotFound();

        return View(destinasi);
    }

    public async Task<IActionResult> DetailArtefak(string id)
    {
        var resultId = IdArtefak.Create(id);
        if (resultId.IsFailure) return BadRequest();

        var artefak = await _repositoriArtefakBudaya.Get(resultId.Value);
        if (artefak is null) return NotFound();

        return View(artefak);
    }

    public async Task<IActionResult> DetailSeni(string id)
    {
        var resultId = IdSeni.Create(id);
        if (resultId.IsFailure) return BadRequest();

        var seni = await _repositoriSeniBudaya.Get(resultId.Value);
        if (seni is null) return NotFound();

        return View(seni);
    }

    public async Task<IActionResult> DetailSitus(string id)
    {
        var resultId = IdSitus.Create(id);
        if (resultId.IsFailure) return BadRequest();

        var situs = await _repositoriSitusBudaya.Get(resultId.Value);
        if (situs is null) return NotFound();

        return View(situs);
    }

    public async Task<IActionResult> DetailUpacara(string id)
    {
        var resultId = IdUpacara.Create(id);
        if (resultId.IsFailure) return BadRequest();

        var upacara = await _repositoriUpacaraBudaya.Get(resultId.Value);
        if (upacara is null) return NotFound();

        return View(upacara);
    }

    public async Task<IActionResult> DetailProdukLokal(string id)
    {
        var resultId = IdProduk.Create(id);
        if (resultId.IsFailure) return BadRequest();

        var produk = await _repositoriProdukLokal.Get(resultId.Value);
        if (produk is null) return NotFound();

        return View(produk);
    }

    [HttpPost]
    public async Task<IActionResult> TambahKomentarArtefak(string id, string nama, string isi, double rating)
    {
        var resultId = IdArtefak.Create(id);
        if(resultId.IsFailure) return BadRequest();

        var artefak = await _repositoriArtefakBudaya.Get(resultId.Value);
        if (artefak is null) return NotFound();

        var komentar = new Komentar
        {
            Id = 0,
            Nama = nama,
            Isi = isi,
            Rating = rating,
            ArtefakBudaya = artefak
        };

        artefak.DaftarKomentar.Add(komentar);

        _repositoriKomentar.Add(komentar);
        _repositoriArtefakBudaya.Update(artefak);

        var result = await _unitOfWork.SaveChangesAsync();
        if(result.IsFailure) return BadRequest();

        return RedirectToAction(nameof(DetailArtefak), new { id });
    }

    [HttpPost]
    public async Task<IActionResult> TambahKomentarSitus(string id, string nama, string isi, double rating)
    {
        var resultId = IdSitus.Create(id);
        if (resultId.IsFailure) return BadRequest();

        var situs = await _repositoriSitusBudaya.Get(resultId.Value);
        if (situs is null) return NotFound();

        var komentar = new Komentar
        {
            Id = 0,
            Nama = nama,
            Isi = isi,
            Rating = rating,
            SitusBudaya = situs
        };

        situs.DaftarKomentar.Add(komentar);

        _repositoriKomentar.Add(komentar);
        _repositoriSitusBudaya.Update(situs);

        var result = await _unitOfWork.SaveChangesAsync();
        if (result.IsFailure) return BadRequest();

        return RedirectToAction(nameof(DetailSitus), new { id });
    }

    [HttpPost]
    public async Task<IActionResult> TambahKomentarSeni(string id, string nama, string isi, double rating)
    {
        var resultId = IdSeni.Create(id);
        if (resultId.IsFailure) return BadRequest();

        var seni = await _repositoriSeniBudaya.Get(resultId.Value);
        if (seni is null) return NotFound();

        var komentar = new Komentar
        {
            Id = 0,
            Nama = nama,
            Isi = isi,
            Rating = rating,
            SeniBudaya = seni
        };

        seni.DaftarKomentar.Add(komentar);

        _repositoriKomentar.Add(komentar);
        _repositoriSeniBudaya.Update(seni);

        var result = await _unitOfWork.SaveChangesAsync();
        if (result.IsFailure) return BadRequest();

        return RedirectToAction(nameof(DetailSeni), new { id });
    }

    [HttpPost]
    public async Task<IActionResult> TambahKomentarUpacara(string id, string nama, string isi, double rating)
    {
        var resultId = IdUpacara.Create(id);
        if (resultId.IsFailure) return BadRequest();

        var upacara = await _repositoriUpacaraBudaya.Get(resultId.Value);
        if (upacara is null) return NotFound();

        var komentar = new Komentar
        {
            Id = 0,
            Nama = nama,
            Isi = isi,
            Rating = rating,
            UpacaraBudaya = upacara
        };

        upacara.DaftarKomentar.Add(komentar);

        _repositoriKomentar.Add(komentar);
        _repositoriUpacaraBudaya.Update(upacara);

        var result = await _unitOfWork.SaveChangesAsync();
        if (result.IsFailure) return BadRequest();

        return RedirectToAction(nameof(DetailUpacara), new { id });
    }
}

src/SidDmb/SidDmb.Web/Views/Atraksi/Artefak.cshtml
@using SidDmb.Domain.MasterDataFunction.ModulBudaya.ArtefakBudayas
@model List<ArtefakBudaya>

@{
    ViewData["Title"] = "Artefak Budaya";
}

<header class="header">
    <div class="section__container header__container" id="home">
        <h1>Artefak Budaya</h1>
    </div>
</header>

<section class="breadcumbs__container ">
    <nav class="breadcrumbs">
        <ul>
            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
            <li><i class="ri-arrow-right-s-line"></i></li>
            <li><a asp-area="" asp-controller="Atraksi" asp-action="Index">Atraksi Wisata</a></li>
            <li><i class="ri-arrow-right-s-line"></i></li>
            <li><a href="">Artefak Budaya</a></li>
        </ul>
    </nav>
</section>

<section class="section__container artefak__container">
    <p class="section__subheader">Warisan Lokal</p>
    <h2 class="section__header">Artefak Budaya</h2>
    <div class="card-gallery">
        @foreach (var artefak in Model)
        {
            <div class="cardku">
                <img src="@artefak.Foto" alt="Image 1">
                <div class="card-content">
                    <div class="category">Artefak @artefak.Kategori.Humanize()</div>
                    <h3 class="title">@artefak.Nama</h3>
                    <p class="description">@artefak.Dekripsi</p>
                    <a asp-area="" asp-controller="Atraksi" asp-action="DetailArtefak" asp-route-id="@artefak.Id.Value" class="read-more">Lihat Lebih Lanjut</a>
                </div>
            </div>
        }
    </div>
</section>

src/SidDmb/SidDmb.Web/Views/Atraksi/Destinasi.cshtml
@using SidDmb.Domain.MasterDataFunction.ModulWisata.DestinasiWisatas

@model List<DestinasiWisata>

@{
    ViewData["Title"] = "Atraksi Wisata | Destinasi Wisata";
}

<header class="header">
    <div class="section__container header__container" id="home">
        <h1>Destinasi Wisata</h1>
    </div>
</header>

<section class="breadcumbs__container ">
    <nav class="breadcrumbs">
        <ul>
            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
            <li><i class="ri-arrow-right-s-line"></i></li>
            <li><a asp-area="" asp-controller="Atraksi" asp-action="Index">Atraksi Wisata</a></li>
            <li><i class="ri-arrow-right-s-line"></i></li>
            <li><a href="">Destinasi Wisata</a></li>
        </ul>
    </nav>
</section>

<section class="section__container destinasi__container">
    <p class="section__subheader">Panduan Wisata</p>
    <h2 class="section__header">Destinasi Wisata</h2>
    <div class="card-gallery">
        @foreach (var destinasi in Model)
        {
            <div class="cardku">
                <img src="@destinasi.Foto" alt="Image 1">
                <div class="card-content">
                    <div class="category">Destinasi @destinasi.Kategori.Humanize()</div>
                    <h3 class="title">@destinasi.Nama</h3>
                    <p class="description">@destinasi.Deskripsi</p>
                    <a asp-area="" asp-controller="Atraksi" asp-action="DetailDestinasi" asp-route-id="@destinasi.Id.Value" class="read-more">Lihat Lebih Lanjut</a>
                </div>
            </div>
        }
    </div>
</section>

src/SidDmb/SidDmb.Web/Views/Atraksi/DetailArtefak.cshtml
@using SidDmb.Domain.MasterDataFunction.ModulBudaya.ArtefakBudayas
@using SidDmb.Web.Controllers
@model ArtefakBudaya

@{
    ViewData["Title"] = "Detail Artefak Budaya";
}

<div class="pembungkus">
    <section class="breadcumbs__container ">
        <nav class="breadcrumbs">
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a asp-area="" asp-controller="Atraksi" asp-action="Index">Atraksi Wisata</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a asp-area="" asp-controller="Atraksi" asp-action="Artefak">Artefak Budaya</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a href="">@Model.Nama</a></li>
            </ul>
        </nav>
    </section>

    <section class="section__container atraksi_container">
        <div class="col-md-4">
            <div class="section">
                <img src="@Model.Foto" alt="Pantai Gilang" class="main-image">
            </div>
        </div>
        <div class="col-md-8">
            <div class="section">
                <div class="grup_kategori_status">
                    <div class="kategori">
                        <p>Artefak @Model.Kategori.Humanize()</p>
                    </div>
                    <div class="status">
                        @if (Model.Ketersediaan == KetersediaanPameran.Ya)
                        {
                            <p><span class="badge" style="background-color: green; color: white;">Tersedia untuk pameran</span></p>
                        }
                        else
                        {
                            <p><span class="badge" style="background-color: green; color: white;">Tidak tersedia untuk pameran</span></p>
                        }
                    </div>
                </div>
                <h2 class="judul">@Model.Nama</h2>
                <p>@Model.Dekripsi</p>
            </div>

            <div class="section">
                <div class="info-grid">
                    <div>
                        <strong>Lokasi Penyimpanan:</strong>
                        <p>@Model.LokasiPenyimpanan</p>
                    </div>
                    <div>
                        <strong>Kondisi Artefak:</strong>
                        <p>@Model.Kondisi.Humanize()</p>
                    </div>
                    <div>
                        <strong>Usia Artefak:</strong>
                        <p>@Model.Usia</p>
                    </div>
                    <div>
                        <strong>Bahan Artefak:</strong>
                        <p>@Model.Bahan</p>
                    </div>
                    <div>
                        <strong>Dimensi Artefak:</strong>
                        <p>@Model.Dimensi</p>
                    </div>
                    <div>
                        <strong>Pemilik/Pengelola</strong>
                        <p>@Model.Pengelola</p>
                    </div>
                    <div>
                        <strong>Nilai Historis:</strong>
                        <p>@Model.NilaiHistoris</p>
                    </div>
                    <div>
                        <strong>Rating:</strong>
                        <p>@Model.Rating.ToString("F1") ★</p>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <section class="section__container komentar__container">
        <div class="grup_judul_tambah_komentar">
            <div class="d-flex" style="gap: 20px; align-items: center;">
                <h4>Komentar Pengunjung</h4>
                <p style="font-weight:500;">@Model.Rating.ToString("F1")★ (@Model.DaftarKomentar.Count Ulasan)</p>
            </div>
        </div>
        <div class="form_komentar">
            <form asp-action="@nameof(AtraksiController.TambahKomentarArtefak)" asp-route-id="@Model.Id.Value">
                <div class="grup_form_komentar">
                    <input type="text" name="nama" id="nama" required placeholder="Nama Anda...">
                    <input type="text" inputmode="numeric" name="rating" id="rating" required placeholder="Rating Anda (0 - 5)...">
                </div>
                <textarea required name="isi" id="isi" placeholder="Tulis komentar Anda..."></textarea>
                <div class="button">
                    <button type="submit">
                        Kirim
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M2 21l21-9L2 3v7l15 2-15 2v7z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
        <div class="kumpulan_komentar">
            @foreach (var komentar in Model.DaftarKomentar)
            {
                <div class="card_komentar">
                    <div class="rating_tanggal_komentar">
                        <h3>@komentar.Nama</h3>
                        <p class="rating_text">@komentar.Rating.ToString("F1")/5 ★</p>
                    </div>
                    <p>@komentar.Isi</p>
                </div>
            }
        </div>
    </section>
</div>

src/SidDmb/SidDmb.Web/Views/Atraksi/DetailDestinasi.cshtml
@using SidDmb.Domain.MasterDataFunction.ModulWisata.DestinasiWisatas
@using SidDmb.Web.Configurations
@model DestinasiWisata

@{
    ViewData["Title"] = $"{Model.Nama} | Destinasi Wisata";
    var cultureInfo = new CultureInfo("id-ID");
}

<div class="pembungkus">
    <section class="breadcumbs__container">
        <nav class="breadcrumbs">
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a asp-area="" asp-controller="Atraksi" asp-action="Index">Atraksi Wisata</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a asp-area="" asp-controller="Atraksi" asp-action="Destinasi">Destinasi Wisata</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a href="">@Model.Nama</a></li>
            </ul>
        </nav>
    </section>

    <section class="section__container atraksi_container">
        <!-- Gambar/Foto -->
        <div class="section">
            <img src="@Model.Foto" alt="Pantai Gilang" class="main-image">
        </div>
        <!-- Kategori, Status, Judul, Deskripsi -->
        <div class="section">
            <div class="grup_kategori_status">
                <div class="kategori">
                    <p>Destinasi @Model.Kategori.Humanize()</p>
                </div>
                <div class="status">
                    <p><span class="badge" style="background-color: orange; color: white; margin-bottom: 0 !important;">@Model.StatusOperasional.Humanize()</span></p>
                </div>
            </div>
            <h2 class="judul">@Model.Nama</h2>
            <p>@Model.Deskripsi</p>
        </div>

        <!-- Informasi Detail -->
        <div class="section">
            <div class="info-grid">
                <div>
                    <strong>Pengelola:</strong>
                    <p>@Model.PengelolaDestinasi</p>
                </div>
                <div>
                    <strong>Lokasi:</strong>
                    <p>@Model.Alamat</p>
                </div>
                <div>
                    <strong>Titik Koordinat:</strong>
                    <p>@Model.TitikKoordinat.Y.ToString("F3"), @Model.TitikKoordinat.X.ToString("F3")</p>
                </div>
                <div>
                    <strong>Aktivitas:</strong>
                    <p>@string.Join(", ", Model.DaftarAktivitas)</p>
                </div>
                <div>
                    <strong>Fasilitas:</strong>
                    <p>@string.Join(", ", Model.DaftarFasilitas)</p>
                </div>
                <div>
                    <strong>Harga Tiket:</strong>
                    <p>@Model.HargaTiketMasuk.ToString("C2", cultureInfo)</p>
                </div>
                <div>
                    <strong>Jam Operasional:</strong>
                    <p>@Model.JamOperasional</p>
                </div>
                <div>
                    <strong>Kontak:</strong>
                    <p>@Model.InformasiKontak</p>
                </div>
                <div>
                    <strong>Popularitas:</strong>
                    <p>@Model.Rating.ToString("F1") ★</p>
                </div>
            </div>
        </div>

        <!-- Peta Lokasi -->
        <div class="section">
            <h2>Peta Lokasi</h2>
            <div class="map">
                <iframe src="@MapsAPIConfiguration.MapsEmbedApi($"{Model.Nama}", Model.TitikKoordinat)"
                        style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </section>
</div>

src/SidDmb/SidDmb.Web/Views/Atraksi/DetailProdukLokal.cshtml
@using SidDmb.Domain.MasterDataFunction.ModulPreneur.ProdukLokals
@model ProdukLokal

@{
    ViewData["Title"] = $"{Model.Nama} | Produk/Kuliner Lokal";
    var cultureInfo = new CultureInfo("id-ID");
}

<div class="pembungkus">
    <section class="breadcumbs__container ">
        <nav class="breadcrumbs">
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a asp-area="" asp-controller="Atraksi" asp-action="Index">Atraksi Wisata</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a asp-area="" asp-controller="Atraksi" asp-action="ProdukLokal">Produk/Kuliner Lokal</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a href="">@Model.Nama</a></li>
            </ul>
        </nav>
    </section>

    <section class="section__container atraksi_container">
        <div class="col-md-4">
            <!-- Gambar/Foto -->
            <div class="section">
                <img src="@Model.MediaPromosi" alt="Pantai Gilang" class="main-image">
            </div>
        </div>
        <div class="col-md-8">
            <!-- Kategori, Status, Judul, Deskripsi -->
            <div class="section">
                <div class="grup_kategori_status">
                    <div class="kategori">
                        <p>Produk @Model.Kategori.Humanize()</p>
                    </div>
                    <div class="status">
                        <p><span class="badge" style="background-color: green; color: white;">@Model.StatusKetersediaan.Humanize()</span></p>
                    </div>
                </div>
                <h2 class="judul">@Model.Nama</h2>
                <p>@Model.Dekripsi</p>
            </div>

            <!-- Informasi Detail -->
            <div class="section">
                <div class="info-grid">
                    <div>
                        <strong>Harga Produk:</strong>
                        <p>@Model.Harga.ToString("C2", cultureInfo)</p>
                    </div>
                    <div>
                        <strong>Unit Usaha Terkait:</strong>
                        <p>@Model.UnitUsaha.Nama</p>
                    </div>
                    <div>
                        <strong>Bahan Utama:</strong>
                        <p>@Model.BahanUtama</p>
                    </div>
                    <div>
                        <strong>Tanggal Produksi Terakhir:</strong>
                        <p>@Model.TanggalProduksiTerakhir.ToString("yyyy-MM-dd")</p>
                    </div>
                    <div>
                        <strong>Tanggal Kadaluarsa:</strong>
                        <p>@Model.TanggalKadaluarsa.ToString("yyyy-MM-dd")</p>
                    </div>
                    <div>
                        <strong>Legalitas & Sertifikasi</strong>
                        <p>@Model.LegalitasDanSertifikat</p>
                    </div>
                    <div>
                        <strong>Kontak Informasi:</strong>
                        <p>@Model.KontakInformasi</p>
                    </div>
                </div>
            </div>
        </div>

    </section>
</div>

src/SidDmb/SidDmb.Web/Views/Atraksi/DetailSeni.cshtml
@using SidDmb.Domain.MasterDataFunction.ModulBudaya.SeniBudayas
@model SeniBudaya

@{
    ViewData["Title"] = $"{Model.Nama} | Seni Budaya";
    var cultureInfo = new CultureInfo("id-ID");
}

<div class="pembungkus">
    <section class="breadcumbs__container ">
        <nav class="breadcrumbs">
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a asp-area="" asp-controller="Atraksi" asp-action="Index">Atraksi Wisata</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a asp-area="" asp-controller="Atraksi" asp-action="Seni">Seni Budaya</a></li>
                <li><i class="ri-arrow-right-s-line"></i></li>
                <li><a href="">@Model.Nama</a></li>
            </ul>
        </nav>
    </section>

    <section class="section__container atraksi_container">
        <!-- Gambar/Foto -->
        <div class="section">
            <img src="@Model.MediaPromosi" alt="Pantai Gilang" class="main-image">
        </div>
        <!-- Kategori, Status, Judul, Deskripsi -->
        <div class="section">
            <div class="grup_kategori_status">
                <div class="kategori">
                    <p>Seni @Model.Kategori.Humanize()</p>
                </div>
            </div>
            <h2 class="judul">@Model.Nama</h2>
            <p>@Model.Dekripsi</p>
        </div>

        <!-- Informasi Detail -->
        <div class="section">
            <div class="info-grid">
                <div>
                    <strong>Nama Pelaku Seni:</strong>
                    <p>@Model.NamaPelakuSeni</p>
                </div>
                <div>
                    <strong>Lokasi Pertunjukan:</strong>
                    <p>@Model.LokasiPertunjukan</p>
                </div>
                <div>
                    <strong>Waktu Pertunjukan:</strong>
                    <p>@Model.WaktuPertunjukan</p>
                </div>
                <div>
                    <strong>Fasilitas Pertunjukan:</strong>
                    <p>@string.Join(", ", Model.FasilitasPertunjukan)</p>
                </div>
                <div>
                    <strong>Durasi Pertunjukan:</strong>
                    <p>@Model.DurasiPentunjukan.TotalHours.ToString("F1") jam</p>
                </div>
                <div>
                    <strong>Harga Tiket:</strong>
                    <p>@Model.HargaTiket.ToString("C2", cultureInfo)</p>
                </div>
                <div>
                    <strong>Popularitas:</strong>
                    <p>@Model.Rating.ToString("F1") ★</p>
                </div>
                <div>
                    <strong>Peraturan Khusus:</strong>
                    <p>@Model.PeraturanKhusus</p>
                </div>
            </div>
        </div>
    </section>
    <section class="section__container komentar__container">
        <div class="grup_judul_tambah_komentar">
            <div class="d-flex" style="gap: 20px; align-items: center;">
                <h4>Komentar Pengunjung</h4>
                <p style="font-weight:500;">@Model.Rating.ToString("F1") ★ (@Model.DaftarKomentar.Count Ulasan)</p>
            </div>
        </div>
        <div class="form_komentar">
            <form asp-action="@nameof(AtraksiController.TambahKomentarSeni)" asp-route-id="@Model.Id.Value">
                <div class="grup_form_komentar">
                    <input type="text" name="nama" id="nama" required placeholder="Nama Anda...">
                    <input type="text" inputmode="numeric" name="rating" id="rating" required placeholder="Rating Anda (0 - 5)...">
                </div>
                <textarea required name="isi" id="isi" placeholder="Tulis komentar Anda..."></textarea>
                <div class="button">
                    <button type="submit">
                        Kirim
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                            <path d="M2 21l21-9L2 3v7l15 2-15 2v7z" />
                        </svg>
                    </button>
                </div>
            </form>
        </div>
        <div class="kumpulan_komentar">
            @foreach (var komentar in Model.DaftarKomentar)
            {
                <div class="card_komentar">
                    <div class="rating_tanggal_komentar">
                        <div class="d-flex" style="gap: 10px;">
                            <h3>@komentar.Nama</h3>
                            <p class="rating_text">@komentar.Rating.ToString("F1")/5 ★</p>
                        </div>
                        @* <h6>26 Desember 2024</h6> *@
                    </div>
                    <p>@komentar.Isi</p>
                </div>
            }
        </div>
    </section>
</div>